services:
  spring-boot-app:
    image: ${DOCKER_USERNAME}/docker-springboot:${IMAGE_TAG:-latest}
    container_name: springboot-app
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      FCM_KEY_PATH: ${FCM_KEY_PATH}
      S3_BUCKET: ${S3_BUCKET}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PW: ${DB_PW}
      DB_DRIVER: ${DB_DRIVER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_SECRET: ${ADMIN_SECRET}
      KAKAO_APP_KEY: ${KAKAO_APP_KEY}
      KAKAO_ADMIN_KEY: ${KAKAO_ADMIN_KEY}
      COOLSMS_API_KEY: ${COOLSMS_API_KEY}
      COOLSMS_API_SECRET: ${COOLSMS_API_SECRET}
      COOLSMS_SENDER: ${COOLSMS_SENDER}
      KAKAO_MAP_API_KEY: ${KAKAO_MAP_API_KEY}
    volumes:
      - /home/ec2-user/app/firebase:/app/firebase:ro
    depends_on:
      - redis
    networks:
      - spring-boot-app-network

  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-boot-app-network

networks:
  spring-boot-app-network:
    driver: bridge