services:
  spring-boot-app:
    image: ${DOCKER_USERNAME}/docker-springboot:${IMAGE_TAG:-latest}
    container_name: springboot-app
    ports:
      - "80:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod
      S3_BUCKET: ${S3_BUCKET}
      DB_URL: ${DB_URL}
      DB_USERNAME: ${DB_USERNAME}
      DB_PW: ${DB_PW}
      DB_DRIVER: ${DB_DRIVER}
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      ADMIN_SECRET: ${ADMIN_SECRET}
      KAKAO_APP_KEY: ${KAKAO_APP_KEY}
      REDIS_HOST: redis
      REDIS_PORT: 6379
      COOLSMS_API_KEY: ${COOLSMS_API_KEY}
      COOLSMS_API_SECRET: ${COOLSMS_API_SECRET}
      COOLSMS_SENDER: ${COOLSMS_SENDER}
    depends_on:
      - redis
    networks:
      - spring-boot-app-network

  redis: # Redis 서비스 추가!
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - spring-boot-app-network

networks:
  spring-boot-app-network:
    driver: bridge