spring:
  jwt:
    secret: ${JWT_SECRET_KEY:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa}

  application:
    name: server

  datasource:
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PW:}
#    driver-class-name: ${DB_DRIVER:org.h2.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        format_sql: true

coolsms:
  api-key: ${COOLSMS-API_KEY}
  api-secret: ${COOLSMS-API_SECRET}
  sender: ${COOLSMS-SENDER}